name: build_usher_trees
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - bte=0.8.3
  - historydag=1.0.1
  - click=8.1.3
  - protobuf=3.19.4
  - frozendict=2.3.4
  - google-api-python-client=2.69.0
  - matplotlib=3.6.2
