name: build_usher_trees
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - bte
  - historydag=1.0.1
  - click
  - protobuf
  - frozendict
  - google-api-python-client
  - matplotlib
